### ISSUE TITLE
About libmodbus

### ISSUE THREAD

**Issue by aogrcs** [Frama-C/open-source-case-studies#2]
Hi, I started to analysis this lib using

```
export FRAMA_C_MEMORY_FOOTPRINT = 8

-include frama-c-path.mk

FRAMAC_CONFIG ?= frama-c-config
FRAMAC_SHARE=$(shell $(FRAMAC_CONFIG) -print-share-path)
include $(shell $(FRAMAC_CONFIG) -print-share-path)/analysis-scripts/frama-c.mk

CPPFLAGS += -include__fc_libc_fixes.h -I src
FCFLAGS  += -machdep gcc_x86_64
EVAFLAGS += \
  -val-use-spec atoi,malloc,free,calloc,Transform,parse_include \
  -eva-equality-domain -eva-gauges-domain -eva-symbolic-locations-domain \
  -slevel 5 \
  -val-warn-on-alarms \
  -val-malloc-functions malloc,realloc,Malloc,Malloc2,Realloc,Realloc2

TARGETS = libmodbus-unit-test-server
all: $(TARGETS:%=%.eva)
help:
	@echo "targets: $(TARGETS)"
loop: $(TARGETS:%=%.parse.loop) $(TARGETS:%=%.eva.loop)
parse: $(TARGETS:%=%.parse)
stats: $(TARGETS:%=%.parse) $(TARGETS:%=%.eva)
	../show_stats.sh "$(notdir $(CURDIR))" $^

libmodbus-unit-test-server.parse: $(sort $(wildcard src/*.c)) tests/unit-test-server.c $(FRAMAC_SHARE)/libc/netdb.c
```

When there is a malloc function in the program, I get red alarms:

    _modbus_init_common Mem_access \valid(&ctx-slave)

Did the built-in malloc not substitute it? Thanks!
BTW, I got shell from chrony!!!
Sincerely

**Comment by maroneze** [comment]
Just to confirm (and to clarify for future readers), the *red alarms* you mention are those in the *Red Alarms* panel, and not "red statuses" (invalid) in the Properties panel. They are closely related, but their semantics are different.

### Purpose of the Red alarms panel

Here's a relevant excerpt from the Eva user manual, in section *Detecting branches abandoned because of red alarms*:

> The Red alarms panel (...). The semantics it implements is the following: if in at least one analysis context, the alarm received an Invalid status (the ACSL property does not hold), then the alarm is present in the panel.

The purpose of the panel is to help prioritize situations where a property has an yellow (unknown) status, but it is *more likely to indicate a problematic issue*. There are several yellow alarms in an analysis, but the ones in the Red alarms panel are more *likely* (again, this is a heuristics) to indicate real issues and therefore should be prioritized. Not all red alarms can (or need to) be removed.

### Analyzing a situation with a red alarm

Here's what I get in the GUI when I run your Makefile, then go to the Red Alarms panel, using Frama-C 17 (Chlorine):

![Frama-C GUI focused on the Red Alarms panel](https://user-images.githubusercontent.com/3179395/43586753-b7cdb2c0-9668-11e8-8d7f-b0979d53a9c5.png)

Looking at the values of variable `ctx` before and after the statement, we notice that the `NULL` value has been eliminated: indeed, if `ctx == NULL`, then `ctx->slave` is invalid. It is clear in this case that the `NULL` case is the one triggering the red alarm: in this state, the dereferencing is invalid. The state becomes BOTTOM (red alarm) and the analysis proceeds with the remaining states.

In the screenshot, however, we cannot immediately see why `ctx` can be `NULL` here. However, with a bit of experience running Eva, you'll soon get used to one of the most common mistakes: *not checking that malloc can fail*.

### People often don't care about `malloc` failing

Most code does not consider that `malloc` can fail, because it's a very rare situation, and often there is not much to be done if it happens, other than just terminating the program. But the C standard does state that `malloc` can fail, and by default that's what Eva's memory allocation builtins do: after calling `malloc`, there are 2 states considered by the analysis, one where it succeeds (and creates variable ctx `__malloc_modbus_new_tcp_l801`), and one where it fails (and returns `NULL`). If you go to line 801 in function `modbus_new_tcp` (the variable naming is very helpful, indicating the allocation site), you'll see the following:

    ctx = (modbus_t *)malloc(sizeof(modbus_t));
    _modbus_init_common(ctx);

There is a call to `malloc`, but no checks to ensure it succeeded.

This mistake is so common that we added an option to Eva: `-no-val-alloc-returns-null`. This is a deviation from the standard, but it works as if the following hypothesis was added to the analysis: *"... and assuming malloc/calloc/realloc never fail..."*. This avoids having to patch a code base with dozens of calls to `malloc`, when the end user does not care about this particular situation.

So, you can either patch the code, or add `-no-val-alloc-returns-null` to the command line, and the red alarm should disappear.

### Checking if a builtin is active by default

To directly answer your question about *did the built-in malloc not substitute it?*: yes, the builtin is active, otherwise I wouldn't have the `__malloc_*` base created. To know whether a given C function is by default replaced with a builtin, you can run `-val-builtins-list`. This will output:

```
*** LIST OF EVA BUILTINS

** Replacements set by -val-builtins-auto:
   unless otherwise specified, function <f> is replaced by builtin Frama_C_<f>:

   __fc_vla_alloc (replaced by: Frama_C_vla_alloc_by_stack),
   __fc_vla_free (replaced by: Frama_C_vla_free), alloca, atan2, atan2f,
   calloc (replaced by: Frama_C_calloc_by_stack), ceil, ceilf, cos, cosf,
   exp, expf, floor, floorf, fmod, fmodf, free, log, log10, log10f, logf,
   malloc (replaced by: Frama_C_malloc_by_stack), memchr, pow, powf,
   rawmemchr, realloc, round, roundf, sin, sinf, sqrt, sqrtf, strchr, strlen,
   strnlen, trunc, truncf

** Full list of builtins (configurable via -val-builtin):
  (...)
```

About `malloc` in particular, we have:

    malloc (replaced by: Frama_C_malloc_by_stack)

So, unless you explicitly add `-no-val-builtins-auto`, or `-val-builtin malloc:<some function>`, the `Frama_C_malloc_by_stack` builtin will be activated.

### Summary

- By default, calling `malloc` creates 2 states in the analyzer, one of which returns `NULL`;
- When evaluating the next statement that uses the result of `malloc`, if there's no check for `NULL`, it will almost always generate a red alarm but remain *unknown* (yellow) in the Properties panel, because one of the states will succeed, but not the other; the consolidation of an *Invalid* state (red) with a *Valid* state (green) is *Unknown*.
- Option `-no-val-alloc-returns-null` allows skipping checks for `malloc` failures.

**Comment by aogrcs** [comment]
Dear maroneze,
Thanks for your detailed explanation! I could proceed with this lib!
